Financas/Financas/Models/Movimentacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Financas.Models
{
    public class Movimentacao
    {
        public virtual Usuario Usuario { get; set; }
        public int Id { get; set; }
        public decimal Valor { get; set; }
        public DateTime Data { get; set; }
        public int UsuarioId { get; set; }
        public Tipo Tipo { get; set; }
    }
}

Financas/Financas/Models/Tipo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Financas.Models
{
    public enum Tipo
    {
        Entrada, Saida
    }
}

Financas/Financas/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Financas.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required, EmailAddress]
        public string Email { get; set; }
    }
}

Financas/Financas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financas.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Financas/Financas/Controllers/UsuarioController.cs
using Financas.DAO;
using Financas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financas.Controllers
{
    public class UsuarioController : Controller
    {
        public UsuarioController(UsuarioDAO dao)
        {
            this.Dao = dao;
        }

        public UsuarioDAO Dao { get; private set; }

        // GET: Usuario
        public ActionResult Index()
        {
            return View(Dao.ListaTodos());
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(Usuario Usuario)
        {
            if (ModelState.IsValid)
            {
                Dao.Adiciona(Usuario);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Form", Usuario);
            }
        }

    }
}

Financas/Financas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Bem Vindo ao Controle Financeiro com ASP.NET MVC</h2>

Financas/Financas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title - Finanças</title>
</head>
<body>
    @Html.Partial("_MenuSuperior")
    <div class="container">
        <main class="col-sm-8">
            @RenderBody()
        </main>
    </div>
</body>
</html>

Financas/Financas/Views/Shared/_MenuSuperior.cshtml
<nav>
    <div class="container-fluid">
        <ul class="nav nav-tabs">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Usuários", "Index", "Usuario")</li>
            <li>@Html.ActionLink("Movimentações", "Index", "Movimentacao")</li>
        </ul>
    </div>
</nav>

Financas/Financas/Views/Usuario/Form.cshtml
@model Financas.Models.Usuario

@using (Html.BeginForm("Adiciona", "Usuario", FormMethod.Post))
{
    @Html.LabelFor(u => u.Nome, "Nome")
    @Html.TextBoxFor(u => u.Nome, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Nome)

    @Html.LabelFor(u => u.Email, "E-mail")
    @Html.TextBoxFor(u => u.Email, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Email)

    <input type="submit" value="Cadastrar" />
}

Financas/Financas/Views/Usuario/Index.cshtml
@model IList<Financas.Models.Usuario>

@Html.ActionLink("Novo usuário", "Form")

<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>E-mail</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var u in Model)
        {
            <tr>
                <td>@u.Id</td>
                <td>@u.Nome</td>
                <td>@u.Email</td>
            </tr>
        }
    </tbody>
</table>